#!/usr/bin/env bash
# This script prints every minute of the day from 00:00 to 23:59

hour=0
while [ $hour -lt 24 ]
do
  minute=0
  while [ $minute -lt 60 ]
  do
    printf "%02d:%02d\n" $hour $minute
    ((minute++))
  done
  ((hour++))
done
